In [2]:
import numpy as np

arr = np.array([[1,3,5],[2,6,8]])

In [3]:
arr

array([[1, 3, 5],
       [2, 6, 8]])

In [4]:
arr.shape

(2, 3)

In [5]:
arr.size

6

In [6]:
arr.ndim

2

In [7]:
arr.dtype

dtype('int64')

In [8]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
np.full((4,5),23)

array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [12]:
np.linspace(1,23,10)

array([ 1.        ,  3.44444444,  5.88888889,  8.33333333, 10.77777778,
       13.22222222, 15.66666667, 18.11111111, 20.55555556, 23.        ])

In [19]:
arr1 = np.array([[1,3,5],[2,6,8]], dtype=np.float64)

In [20]:
arr1.dtype

dtype('float64')

In [22]:
arr2 = arr1.astype(np.int64)
arr2.dtype


dtype('int64')

In [23]:
new = arr.reshape(6,1)

In [24]:
new

array([[1],
       [3],
       [5],
       [2],
       [6],
       [8]])

In [25]:
arr.flatten()

array([1, 3, 5, 2, 6, 8])